[project]
name = "mlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.0",
    "nltk>=3.9.1",
    "numpy>=2.2.1",
    "scipy>=1.15.0",
    "seaborn>=0.13.2",
]
